<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Elastic Search Base for Magento 2
 */ //phpcs:ignore Magento2.Legacy.PhtmlTemplate.TextJavascriptTypeFound ?>
<script type="text/javascript">
    require(
        [
            'Magento_Ui/js/lib/validation/validator',
            'jquery',
            'mage/translate'
        ], function(validator, $){

            validator.addRule('validate-stop-word', function (value) {
                return value.match(/^[^\s]+$/g);
            }, $.mage.__('Stop words should not contain whitespaces.')
        );
    });
</script>
