<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
 * @package Improved Layered Navigation Base for Magento 2
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\SwatchesChoose $block */
?>

<script type="text/x-magento-init">
    {
        ".products-grid, .products-list": {
            "amShopbySwatchesChoose": {
                "listSwatches": <?= /* @noEscape */ $block->getSwatchesByJson();?>
            }
        }
    }
</script>
