<?php
// @codingStandardsIgnoreFile
?>
<?php $helper = $this->helper('WeltPixel\GA4\Helper\Data'); ?>
<?php $ga4ServerSideHelper = $this->helper('WeltPixel\GA4\Helper\ServerSideTracking'); ?>
<?php if ($this->isEnabled()) : ?>

    <?php if (!($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_CART)
        && $ga4ServerSideHelper->isDataLayerEventDisabled())) : ?>

        <?php
            $products = $this->getProducts();
            $this->setDataLayerOption('event', 'view_cart');
            $this->setDataLayerOption('cart_total', number_format($this->getCartTotal(), 2, '.', ''));
            $this->setDataLayerOption('total', number_format($this->getCartTotal(), 2, '.', ''));
            $this->setDataLayerOption('currency', $this->getCurrencyCode());
            $this->setEcommerceData('items', $products);
        ?>

    <?php endif; ?>

        <?php

    if (!($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_ITEM_LIST)
        && $ga4ServerSideHelper->isDataLayerEventDisabled())) :

            $crosselProductsCollection = $this->getCrosselProductCollection();
            $productImpressions = [];

            if (count($crosselProductsCollection)) :
                $i = 1;
                foreach ($crosselProductsCollection as $_product) :
                    $crosselProduct = [];
                    $crosselProduct['item_name'] = html_entity_decode($_product->getName());
                    $crosselProduct['item_id'] = $helper->getGtmProductId($_product);
                    $crosselProduct['price'] = number_format($_product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', '');
                    if ($helper->isBrandEnabled()) :
                        $crosselProduct['item_brand'] = $helper->getGtmBrand($_product);
                    endif;
                    $ga4Categories = $helper->getGA4CategoriesFromCategoryIds($_product->getCategoryIds());
                    $crosselProduct = array_merge($crosselProduct, $ga4Categories);
                    $crosselProduct['item_list_name'] = __('Crossel Products');
                    $crosselProduct['item_list_id'] = __('crossel_products');
                    $crosselProduct['index'] = $i;
                    $crosselProduct['currency'] = $this->getCurrencyCode();
                    $productImpressions[] = $crosselProduct;
                    $i++;
                endforeach;
            endif;

            if (count($productImpressions)) :
                $impressionData = [];
                $impressionData['event'] = 'view_item_list';
                $impressionData['ecommerce'] = [];
                $impressionData['ecommerce']['items'] = $productImpressions;
                $this->setAdditionalDataLayerData($impressionData);
            endif;
        endif;

        if ($helper->isAdWordsRemarketingEnabled()):
            $remarketingData = [];
            $remarketingData['ecomm_pagetype'] = \WeltPixel\GA4\Model\Api\Remarketing::ECOMM_PAGETYPE_CART;
            $remarketingData['ecomm_prodid'] = $this->getProductIds();
            $remarketingData['ecomm_totalvalue'] = number_format($this->getCartTotal(), 2, '.', '');
            $this->setDataLayerOption('google_tag_params', $remarketingData);
        endif;

        ?>
<?php endif; ?>
<?php if ($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_ITEM_LIST)) : ?>
<?php
    $crosselProductsCollection = $this->getCrosselProductCollection();
    $productImpressions = [];

    if (count($crosselProductsCollection)) :
        $i = 1;
        foreach ($crosselProductsCollection as $_product) :
            $crosselProduct = [];
            $crosselProduct['item_name'] = html_entity_decode($_product->getName());
            $crosselProduct['item_id'] = $helper->getGtmProductId($_product);
            $crosselProduct['price'] = number_format($_product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', '');
            if ($helper->isBrandEnabled()) :
                $crosselProduct['item_brand'] = $helper->getGtmBrand($_product);
            endif;
            $ga4Categories = $helper->getGA4CategoriesFromCategoryIds($_product->getCategoryIds());
            $crosselProduct = array_merge($crosselProduct, $ga4Categories);
            $crosselProduct['item_list_name'] = __('Crossel Products');
            $crosselProduct['item_list_id'] = __('crossel_products');
            $crosselProduct['index'] = $i;
            $crosselProduct['quantity'] = 1;
            $crosselProduct['currency'] = $this->getCurrencyCode();
            $crosselProduct['affiliation'] = $ga4ServerSideHelper->getAffiliationName();
            /** Set the custom dimensions */
            $customDimensions = $this->getProductDimensions($_product);
            foreach ($customDimensions as $name => $value) :
                $crosselProduct[$name] = $value;
            endforeach;
            $productImpressions[] = $crosselProduct;
            $i++;
        endforeach;
    endif;

    if (count($productImpressions)) :
        $impressionData = [];
        $impressionData['params'] = [
            'item_list_id' => __('crossel_products'),
            'item_list_name' => __('Crossel Products'),
            'items' => $productImpressions
        ];
        $this->setServerSideViewItemList($impressionData);
    endif;
?>
<?php endif; ?>
