<?php
// @codingStandardsIgnoreFile
$ga4ServerSideHelper = $this->helper('WeltPixel\GA4\Helper\ServerSideTracking');
$helper = $this->helper('WeltPixel\GA4\Helper\Data');
?>
<?php if($this->isEnabled()) : ?>
<?php if (!($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_ITEM_LIST)
    && $ga4ServerSideHelper->isDataLayerEventDisabled())) : ?>
        <?php $productCollection = $this->getProductCollection(); ?>
        <?php if (count($productCollection)) : ?>
            <?php $categoryProducts = array(); ?>
            <?php $listValue = ($block->getListPrefix()) ? $block->getListPrefix() . ' ' . __('Search Result') : __('Search Result'); ?>
            <?php $i = 1; ?>
            <?php foreach($productCollection as $product) : ?>
                <?php $categoryProduct = []; ?>
                <?php $categoryProduct['item_name'] = html_entity_decode($product->getName()); ?>
                <?php $categoryProduct['item_id'] = $helper->getGtmProductId($product); ?>
                <?php $categoryProduct['price'] = number_format($product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', ''); ?>
                <?php if ($helper->isBrandEnabled()) : ?>
                    <?php $categoryProduct['item_brand'] = $helper->getGtmBrand($product); ?>
                <?php endif;?>
                <?php $ga4Categories = $helper->getGA4CategoriesFromCategoryIds($product->getCategoryIds()); ?>
                <?php $categoryProduct = array_merge($categoryProduct, $ga4Categories); ?>
                <?php $categoryProduct['item_list_name'] = $listValue; ?>
                <?php $categoryProduct['item_list_id'] =  str_replace(' ', '_', strtolower($listValue)); ?>
                <?php $categoryProduct['index'] = $i; ?>
                <?php $categoryProduct['currency'] = $this->getCurrencyCode(); ?>
                <?php $categoryProducts[] = $categoryProduct; ?>
                <?php $i++ ; ?>
            <?php endforeach; ?>
            <?php $this->setEcommerceData('items', $categoryProducts); ?>
            <?php $this->setDataLayerOption('event', 'view_item_list'); ?>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($helper->isAdWordsRemarketingEnabled()): ?>
        <?php
        $remarketingData = [];
        $remarketingData['ecomm_pagetype'] = \WeltPixel\GA4\Model\Api\Remarketing::ECOMM_PAGETYPE_SEARCHRESULTS;
        ?>
        <?php $this->setDataLayerOption('google_tag_params', $remarketingData); ?>
    <?php endif; ?>

<?php endif; ?>
<?php if ($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_ITEM_LIST)) : ?>
    <?php $productCollection = $this->getProductCollection(); ?>
    <?php if (count($productCollection)) : ?>
        <?php $categoryProducts = array(); ?>
        <?php $listValue = ($block->getListPrefix()) ? $block->getListPrefix() . ' ' . __('Search Result') : __('Search Result'); ?>
        <?php $i = 1; ?>
        <?php foreach($productCollection as $product) : ?>
            <?php $categoryProduct = []; ?>
            <?php $categoryProduct['item_name'] = html_entity_decode($product->getName()); ?>
            <?php $categoryProduct['item_id'] = $helper->getGtmProductId($product); ?>
            <?php $categoryProduct['price'] = number_format($product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', ''); ?>
            <?php if ($helper->isBrandEnabled()) : ?>
                <?php $categoryProduct['item_brand'] = $helper->getGtmBrand($product); ?>
            <?php endif;?>
            <?php $ga4Categories = $helper->getGA4CategoriesFromCategoryIds($product->getCategoryIds()); ?>
            <?php $categoryProduct = array_merge($categoryProduct, $ga4Categories); ?>
            <?php $categoryProduct['item_list_name'] = $listValue; ?>
            <?php $categoryProduct['item_list_id'] =  str_replace(' ', '_', strtolower($listValue)); ?>
            <?php $categoryProduct['index'] = $i; ?>
            <?php $categoryProduct['quantity'] = 1; ?>
            <?php $categoryProduct['currency'] = $this->getCurrencyCode(); ?>
            <?php $categoryProduct['affiliation'] = $ga4ServerSideHelper->getAffiliationName(); ?>
            <?php
            /** Set the custom dimensions */
            $customDimensions = $this->getProductDimensions($product);
            foreach ($customDimensions as $name => $value) :
                $categoryProduct[$name] = $value;
            endforeach;
            ?>
            <?php $categoryProducts[] = $categoryProduct; ?>
            <?php $i++ ; ?>
        <?php endforeach; ?>
        <?php if (count($categoryProducts)) : ?>
            <?php
            $impressionData = [];
            $impressionData['params'] = [
                'item_list_id' => str_replace(' ', '_', strtolower($listValue)),
                'item_list_name' => $listValue,
                'items' => $categoryProducts
            ];
            $this->setServerSideViewItemList($impressionData);
            ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
